# Generated by Django 4.0.5 on 2022-08-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('slug', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
